ecommerce/cart/urls.py
from django.contrib import admin
from django.urls import path,include

from cart import views
app_name='cart'

urlpatterns = [
    path('addcart/<int:i>',views.AddCartView.as_view(),name='addcart'),
    path('cartview',views.CartView.as_view(),name='cartview'),
    path('decrementcart/<int:i>',views.DecrementCartView.as_view(),name='deccart'),
    path('removecart/<int:i>',views.RemoveCartView.as_view(),name='removecart'),
    path('orderform',views.OrderFormView.as_view(),name='orderform'),
    path('paymentsuccess/<i>',views.PaymentSuccessView.as_view(),name='paymentsuccess'),
    path('ordersummary',views.OrderSummaryView.as_view(),name='ordersummary')
]

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('shop.urls')),
    path('cart/',include('cart.urls'))
]

from django.conf.urls.static import static
from django.conf import settings

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

ecommerce/shop/urls.py
from django.contrib import admin
from django.urls import path

from shop import views
app_name='shop'

urlpatterns = [
    path('',views.CategoryView.as_view(),name='categories'),
    path('products/<int:i>',views.ProductsView.as_view(),name='products'),
    path('prod_detail/<int:i>',views.ProductDetailView.as_view(),name='proddetail'),
    path('signup',views.SignupView.as_view(),name='signup'),
    path('otp',views.OtpVerficationView.as_view(),name='otpverify'),
    path('signin',views.SigninView.as_view(),name='signin'),
    path('signout',views.SignoutView.as_view(),name='signout'),
    path('addcategory',views.AddCategoryView.as_view(),name='addcategory'),
    path('addproduct',views.AddProductView.as_view(),name='addproduct')
]

ecommerce/cart/models.py
from django.db import models

from shop.models import CustomUser,Product

class Cart(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE) # one user can buy many products
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField(default=1)
    date_added=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.product.name

    def subtotal(self):
        return self.quantity*self.product.price


from django.utils import timezone
class Order(models.Model):
    user=models.ForeignKey(CustomUser,on_delete=models.CASCADE)
    address=models.TextField()
    phone=models.IntegerField()
    payment_method=models.CharField()
    order_id=models.CharField(null=True)
    is_ordered=models.BooleanField(default=False)
    amount=models.IntegerField(null=True)
    ordered_date=models.DateTimeField(default=timezone.now)
    delivery_status=models.BooleanField(default=False)

    def __str__(self):
        return str(self.order_id)


class Order_items(models.Model):
    order=models.ForeignKey(Order,on_delete=models.CASCADE,related_name='items')
    product=models.ForeignKey(Product,on_delete=models.CASCADE)
    quantity=models.IntegerField()

ecommerce/cart/forms.py
from django import forms

from cart.models import Order
from django.forms import RadioSelect


class OrderForm(forms.ModelForm):
    choices=(('COD','COD'),('ONLINE','ONLINE'))
    payment_method=forms.ChoiceField(choices=choices,widget=RadioSelect)
    class Meta:
        model=Order
        fields=['address','phone','payment_method']

ecommerce/cart/views.py
from django.shortcuts import render,redirect

# Create your views here.

from django.views import View

from cart.models import Cart
from shop.models import Product

from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
@method_decorator(login_required,name='dispatch')
class AddCartView(View):
    def get(self,request,i):
        u=request.user
        p=Product.objects.get(id=i)
        try:
            c=Cart.objects.get(user=u,product=p)
            c.quantity+=1
            c.save()
        except:
            c=Cart.objects.create(user=u,product=p,quantity=1)
            c.save()

        return redirect('cart:cartview')


from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
@method_decorator(login_required,name='dispatch')
class CartView(View):
    def get(self,request):
        u=request.user
        c=Cart.objects.filter(user=u)
        total=0
        for i in c:
            total+=i.quantity*i.product.price
        return render(request,'cart.html',{'cart':c,'total':total})


class DecrementCartView(View):
    def get(self,request,i):
        u=request.user
        p=Product.objects.get(id=i)
        c=Cart.objects.get(user=u,product=p)
        if c.quantity>1:
            c.quantity-=1
            c.save()
        else:
            c.delete()

        return redirect('cart:cartview')


class RemoveCartView(View):
    def get(self,request,i):
        u=request.user
        p=Product.objects.get(id=i)
        c=Cart.objects.get(user=u,product=p)
        c.delete()

        return redirect('cart:cartview')


def check_stock(c):
    stock=True
    for i in c:
        if i.product.stock<i.quantity:
            stock=False
            break
    return stock

from cart.forms import OrderForm
from cart.models import Order_items
import razorpay
from django.contrib import messages
class OrderFormView(View):
    def get(self,request):
        form_instance=OrderForm()
        return render(request,'orderform.html',{'form':form_instance})

    def post(self,request):
        form_instance=OrderForm(request.POST)
        if form_instance.is_valid():
            order_obj=form_instance.save(commit=False)
            u = request.user
            order_obj.user=u
            order_obj.save()
            c=Cart.objects.filter(user=u)
            stock=check_stock(c) # to check the stock before the order

            if stock:
                for i in c:
                    o=Order_items.objects.create(order=order_obj,product=i.product,quantity=i.quantity)
                    o.save()

                total=0
                for i in c:
                    total+=i.quantity*i.product.price

                if order_obj.payment_method=='ONLINE':
                # RAZOR PAYMENT : online payment gateway

                    #create client connection
                    client=razorpay.Client(auth=('rzp_test_6gbGoBUyWtAO14','KbPJOTMaiSgmwBL5xH4DW3YY'))

                    #order creation
                    response_payment=client.order.create(dict(amount=total*100,currency='INR'))

                    print(response_payment)

                    order_id=response_payment['id']
                    order_obj.order_id=order_id
                    order_obj.is_ordered=False
                    order_obj.amount=total
                    order_obj.save()

                elif order_obj.payment_method=='COD':
                    order_obj.is_ordered=True
                    order_obj.save()

                    items = Order_items.objects.filter(order=order_obj)
                    for i in items:
                        i.product.stock -= i.quantity  # to decrement the stock after the order is completed
                        i.product.save()

                    # to delete the cart of the current user
                    c = Cart.objects.filter(user=u)
                    c.delete()

                    return redirect('shop:categories')

                else:
                    pass

                return render(request,'payment.html',{'payment':response_payment,'name':u.username})

            else:
                messages.error(request,'Currently item is not available')
                return render(request,'payment.html')


from django.utils.decorators import method_decorator
from django.views.decorators.csrf import csrf_exempt
from shop.models import CustomUser
from django.contrib.auth import login
from cart.models import Order,Order_items
@method_decorator(csrf_exempt,name='dispatch') #to avoid csrf token error
class PaymentSuccessView(View):
    def post(self,request,i):
        user=CustomUser.objects.get(username=i)
        login(request, user) # to add the current user to the session agin

        response=request.POST #payment confirmation sent by razorpay to our app
                                # order_id,payment_id,signature
        print(response)

        o=Order.objects.get(order_id=response['razorpay_order_id'])
        o.is_ordered=True
        o.save()

        # to change the stock
        items=Order_items.objects.filter(order=o)
        for i in items:
            i.product.stock-=i.quantity # to decrement the stock after the order is completed
            i.product.save()

        # to delete the cart of the current user
        c=Cart.objects.filter(user=user)
        c.delete()

        return render(request,'payment_success.html')


class OrderSummaryView(View):
    def get(self,request):
        u=request.user
        o=Order.objects.filter(user=u,is_ordered=True)
        return render(request,'ordersummary.html',{'orders':o})

ecommerce/templates/addcategory.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add Category</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Add Category </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>

<div class="container w-50 border border-1 border-dark shadow px-5 pb-5 pt-5 mt-3 mb-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
</div>


{% endblock %}

ecommerce/templates/addproduct.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Add Product</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Add Product </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>

<div class="container w-50 border border-1 border-dark shadow px-5 pb-5 pt-5 mt-3 mb-5">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
</div>


{% endblock %}

ecommerce/templates/cart.html
{% extends 'base.html' %}
{% block content %}

<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Cart</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Cart</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- End All Title Box -->
{{cart}}
    <!-- Start Cart  -->
    <div class="cart-box-main">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="table-main table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                    <th>Product Name</th>
                                    <th>Unite Price</th>
                                    <th>Quantity</th>
                                    <th>Sub Total</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>

                                {% for i in cart %}
                                    <tr>
                                        <td class="thumbnail-img">
                                            <a href="#">
                                        <img class="img-fluid" src="{{i.product.image.url}}" alt="" />
                                        </a>
                                        </td>
                                        <td class="name-pr">
                                            <a href="#">
                                                {{i.product.name}}
                                            </a>
                                        </td>
                                        <td class="price-pr">
                                            <p>AED{{i.product.price}}</p>
                                        </td>
                                        <td class="quantity-box">{{i.quantity}}</td>
                                        <td class="total-pr">
                                            <p>{{i.subtotal}}</p>
                                        </td>
                                        <td class="remove-pr" >

                                            {% if i.product.stock > 0 %}
                                                <a href="{% url 'cart:addcart' i.product.id %}" >
                                                    <i class="fa-solid fa-plus"></i>
                                                </a>
                                                 <a href="{% url 'cart:deccart' i.product.id %}">
                                                    <i class="fa-solid fa-minus"></i>
                                                </a>
                                                <a href="{% url 'cart:removecart' i.product.id %}">
                                                    <i class="fa-solid fa-xmark"></i>
                                                </a>
                                            {% else %}
                                                <a href="{% url 'cart:deccart' i.product.id %}">
                                                    <i class="fa-solid fa-minus"></i>
                                                </a>
                                                <a href="{% url 'cart:removecart' i.product.id %}">
                                                    <i class="fa-solid fa-xmark"></i>
                                                </a>
                                            {% endif %}

                                        </td>
                                    </tr>
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

            <div class="row my-5">
                <div class="col-lg-8 col-sm-12"></div>
                <div class="col-lg-4 col-sm-12">
                    <div class="order-box">
                        <h3>Order summary</h3>
                        <div class="d-flex">
                            <h4>Sub Total</h4>
                            <div class="ml-auto font-weight-bold"> {{total}} </div>
                        </div>

                        <div class="d-flex">
                            <h4>Shipping Cost</h4>
                            <div class="ml-auto font-weight-bold"> Free </div>
                        </div>
                        <hr>
                        <div class="d-flex gr-total">
                            <h5>Grand Total</h5>
                            <div class="ml-auto h5"> AED {{total}} </div>
                        </div>
                        <hr> </div>
                </div>
                <div class="col-12 d-flex shopping-box"><a href="{% url 'cart:orderform' %}" class="ml-auto btn hvr-hover">Checkout</a> </div>
            </div>

        </div>
    </div>

{% endblock %}

ecommerce/templates/categories.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<!-- Start Slider -->
    <div id="slides-shop" class="cover-slides">
        <ul class="slides-container">
            <li class="text-center">
                <img src="{% static 'images/banner-01.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-02.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
            <li class="text-center">
                <img src="{% static 'images/banner-03.jpg' %}" alt="">
                <div class="container">
                    <div class="row">
                        <div class="col-md-12">
                            <h1 class="m-b-20"><strong>Welcome To <br> Freshshop</strong></h1>
                            <p class="m-b-40">See how your users experience your website in realtime or view <br> trends to see any changes in performance over time.</p>
                            <p><a class="btn hvr-hover" href="#">Shop New</a></p>
                        </div>
                    </div>
                </div>
            </li>
        </ul>
        <div class="slides-navigation">
            <a href="#" class="next"><i class="fa fa-angle-right" aria-hidden="true"></i></a>
            <a href="#" class="prev"><i class="fa fa-angle-left" aria-hidden="true"></i></a>
        </div>
    </div>
    <!-- End Slider -->

<div class="container w-50 p-5">
    <h1 class="text-center">OUR COLLECTIONS</h1>
    <p><b>Welcome to Freshop – Your Neighborhood Grocery, Online!</b>
        Discover the freshest produce, pantry staples, and everyday essentials – all delivered to your doorstep.
        Freshop brings your local grocery store online with easy ordering, personalized deals, and fast,
        convenient service. Shop smart. Shop fresh. Shop Freshop.
    </p>
</div>
<div class="categories-shop">
    <div class="container">
        <div class="row">
            {% for i in category %}
                <div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
                    <div class="shop-cat-box">
                        <img  src="{{i.image.url}}" height="300px" width="100%" />
                        <a class="btn hvr-hover" href="{% url 'shop:products' i.id %}">{{i.name}}</a>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock %}

ecommerce/templates/login.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Signup</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Signup </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>

<div class="container w-50 border border-1 border-dark shadow px-5 pb-5 pt-5 mt-3 mb-5">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
</div>


{% endblock %}

ecommerce/templates/ordersummary.html
{% extends 'base.html' %}
{% block content %}

<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Order Summary</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Order Summary </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>

<div class="container text-center mt-3">
<h3>Name of the customer: {{user.username}}</h3>
</div>

{% for i in orders %}
    {% for j in i.items.all %}
        <div class="card mb-3 mx-auto mt-3" style="max-width: 700px;">
          <div class="row g-0">
            <div class="col-md-4">
              <img src="{{j.product.image.url}}" class="rounded-start p-3" height="150px" width="100%" alt="...">
            </div>
            <div class="col-md-8">
              <div class="card-body">
                <h5 class="card-title fs-5"><b>Product Name: {{j.product.name}}</b></h5>
                <p class="card-text">Quantity: {{j.quantity}}</p>
                <p class="card-text">Price: {{j.product.price}}</p>
                <p class="card-text">Order ID: {{i.order_id}}</p>
                <p class="card-text">Ordered Date: {{i.ordered_date}}</p>
                <p class="card-text">Delievery Status: {{i.delivery_status}}</p>

              </div>
            </div>
          </div>
        </div>
    {% endfor %}
{% endfor %}

{% endblock %}

ecommerce/templates/otp.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>OTP Verification</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">otp </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>


<div class="container w-50 border border-1 border-dark shadow px-5 pb-5 pt-5 mt-3 mb-5">
    <h1>Enter the OTP</h1>
    <form method="POST">
        {% csrf_token %}
        <input type="text" name="otp">
        <input type="submit">
    </form>

    {% if messages %}
        {% for m in messages %}
            {{m}}
        {% endfor %}
    {% endif %}

</div>


{% endblock %}

ecommerce/templates/payment.html
{% extends 'base.html' %}
{% block content %}

<div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Razorpay Payment</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Razorpay</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

{% if messages %}
    {% for i in messages %}
        {{i}}
    {% endfor %}

{% else %}
    <div class="container w-50 mt-5 p-5 text-center">
        <form action="{% url 'cart:paymentsuccess' name %}" method="POST">
            {% csrf_token %}
        <script
           src="https://checkout.razorpay.com/v1/checkout.js"
            data-key="rzp_test_6gbGoBUyWtAO14" // Enter the Test API Key ID generated from Dashboard → Settings → API Keys
            data-amount="{{payment.amount}}" // Amount is in currency subunits. Hence, 29935 refers to 29935 paise or ₹299.35.
            data-currency="INR"// You can accept international payments by changing the currency code. Contact our Support Team to enable International for your account
            data-order_id="{{payment.id}}"// Replace with the order_id generated by you in the backend.
            data-buttontext="Pay with Razorpay"
            data-name="Acme Corp"
            data-description="A Wild Sheep Chase is the third novel by Japanese author Haruki Murakami"
            data-image="https://example.com/your_logo.jpg"
            data-prefill.name="{{name}}"
            data-prefill.email="{{user.email}}"
            data-theme.color="#F37254"
        ></script>
        <input type="hidden" custom="Hidden Element" name="hidden"/>
        </form>
    </div>
{% endif %}
{% endblock %}

ecommerce/templates/payment_success.html
{% extends 'base.html' %}
{% block content %}
<h1>Payment Successful</h1>
{% endblock %}

ecommerce/templates/prod_detail.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Shop Detail</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Shop Detail </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>
    <!-- End All Title Box -->
{{product}}
    <!-- Start Shop Detail  -->
    <div class="shop-detail-box-main">
        <div class="container">
            <div class="row">
                <div class="col-xl-5 col-lg-5 col-md-6">
                    <div id="carousel-example-1" class="single-product-slider carousel slide" data-ride="carousel">
                        <div class="carousel-inner" role="listbox">
                            <div class="carousel-item active"> <img class="d-block w-100" src="{{product.image.url}}" height="400px" alt="First slide"> </div>
                        </div>
                    </div>
                </div>
                <div class="col-xl-7 col-lg-7 col-md-6">
                    <div class="single-product-details">
                        <h2>{{product.name}}</h2>
                        <h5>{{product.price}}AED</h5>
                        <p class="available-stock">

                            {% if product.stock > 0 %}
                                <span>{{product.stock}} items available</span><p>
                            {% endif %}

						<h4>Short Description:</h4>
						<p style="text-align:justify;">{{product.description}}</p>

						<div class="price-box-bar">
							<div class="cart-and-bay-btn">
                                {% if user.is_authenticated %}
                                    {% if user.is_superuser == True %}
                                        <a class="btn hvr-hover" data-fancybox-close="" href="">Add to Stock</a>
                                    {% else %}
								        {% if product.stock > 0 %}
								            <a class="btn hvr-hover" data-fancybox-close="" href="{% url 'cart:addcart' product.id %}">Add to cart</a>
                                        {% else %}
                                            <h3>Out Of Stock</h3>
                                        {% endif %}
                                    {% endif %}
                                {% endif %}
							</div>
						</div>

<!--						<div class="add-to-btn">-->
<!--							<div class="add-comp">-->
<!--								<a class="btn hvr-hover" href="#"><i class="fas fa-heart"></i> Add to wishlist</a>-->
<!--								<a class="btn hvr-hover" href="#"><i class="fas fa-sync-alt"></i> Add to Compare</a>-->
<!--							</div>-->
<!--							<div class="share-bar">-->
<!--								<a class="btn hvr-hover" href="#"><i class="fab fa-facebook" aria-hidden="true"></i></a>-->
<!--								<a class="btn hvr-hover" href="#"><i class="fab fa-google-plus" aria-hidden="true"></i></a>-->
<!--								<a class="btn hvr-hover" href="#"><i class="fab fa-twitter" aria-hidden="true"></i></a>-->
<!--								<a class="btn hvr-hover" href="#"><i class="fab fa-pinterest-p" aria-hidden="true"></i></a>-->
<!--								<a class="btn hvr-hover" href="#"><i class="fab fa-whatsapp" aria-hidden="true"></i></a>-->
<!--							</div>-->
<!--						</div>-->
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

ecommerce/templates/products.html
{% extends 'base.html' %}
{% block content %}
<div class="container-fluid">
    <img src="{{category.image.url}}" height="400px" width="100%">
</div>
<div class="container w-50 p-5">
    <h1 class="text-center">{{category.name}}</h1>
    <p>{{category.description}}</p>
</div>

<div class="products-box">
        <div class="container">
            <div class="row special-list">
                {% for i in category.products.all %}
                    <div class="col-lg-3 col-md-6 special-grid best-seller">
                        <div class="products-single fix">
                            <div class="box-img-hover">
                                <div class="type-lb">
                                    <p class="sale">Sale</p>
                                </div>
                                <img src="{{i.image.url}}" class="img-fluid" alt="Image">
                                <div class="mask-icon">
                                    <ul>
                                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="View"><i class="fas fa-eye"></i></a></li>
                                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Compare"><i class="fas fa-sync-alt"></i></a></li>
                                        <li><a href="#" data-toggle="tooltip" data-placement="right" title="Add to Wishlist"><i class="far fa-heart"></i></a></li>
                                    </ul>
                                    <a class="cart" href="{% url 'shop:proddetail' i.id %}">Details</a>
                                </div>
                            </div>
                            <div class="why-text">
                                <h4>{{i.name}}</h4>
                                <h5>{{i.price}}</h5>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
</div>

{% endblock %}

ecommerce/templates/signup.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}

   <div class="all-title-box">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h2>Signup</h2>
                    <ul class="breadcrumb">
                        <li class="breadcrumb-item"><a href="#">Shop</a></li>
                        <li class="breadcrumb-item active">Signup </li>
                    </ul>
                </div>
            </div>
        </div>
   </div>

<div class="container w-50 border border-1 border-dark shadow px-5 pb-5 pt-5 mt-3 mb-5">
    <form method="POST">
        {% csrf_token %}
        {{form|crispy}}
        <input type="submit">
    </form>
</div>


{% endblock %}